<?php

namespace App\Models;

use Encore\Admin\Auth\Database\Administrator as Administrator;
use Encore\Admin\Traits\ModelTree;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class AdminUser extends Administrator
{
    use HasApiTokens;
    use Notifiable;
    use ModelTree {
        ModelTree::boot as treeBoot;
    }

    protected $fillable = ['username', 'password', 'email', 'name','first_name','family_name', 'avatar', 'mobile_no', 'organization_id', 'department_id', 'account_type', 'parent_id', 'active_status','country_id'];

    public function user_detail()
    {
        return $this->hasOne(EWUserDetail::class, 'user_id');
    }

    /**
     * set username column for login
     *
     */
    public function findForPassport($username)
    {
        return $this->where('username', $username)
                    ->first()
        ;
    }


    public function delete()
    {
        //delete user details
        EWUserDetail::where('user_id', $this->id)
                    ->delete()
        ;
        //user Activity Limit
        EWUserActivityLimit::where('user_id', $this->id)
                           ->delete()
        ;
        //user Activity logs
        EWUserActivityLimitLog::where('user_id', $this->id)
                              ->delete()
        ;
        //ew_user_config
        EWUserConfig::where('user_id', $this->id)
                    ->delete()
        ;
        //user config log
        EWUserConfigLog::where('user_id', $this->id)
                       ->delete()
        ;
        //user limit Config
        EWUserLimitConfig::where('user_id', $this->id)
                         ->delete()
        ;
        //user limit config log
        EWUserLimitConfigLog::where('user_id', $this->id)
                            ->delete()
        ;
        //user Subscription
        UserSubscription::where('user_id', $this->id)
                        ->delete()
        ;
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
